var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.arrayIteratorImpl=function(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}};$jscomp.arrayIterator=function(a){return{next:$jscomp.arrayIteratorImpl(a)}};$jscomp.makeIterator=function(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return b?b.call(a):$jscomp.arrayIterator(a)};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;
$jscomp.ISOLATE_POLYFILLS=!1;$jscomp.FORCE_POLYFILL_PROMISE=!1;$jscomp.FORCE_POLYFILL_PROMISE_WHEN_NO_UNHANDLED_REJECTION=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a};
$jscomp.getGlobal=function(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");};$jscomp.global=$jscomp.getGlobal(this);$jscomp.IS_SYMBOL_NATIVE="function"===typeof Symbol&&"symbol"===typeof Symbol("x");$jscomp.TRUST_ES6_POLYFILLS=!$jscomp.ISOLATE_POLYFILLS||$jscomp.IS_SYMBOL_NATIVE;$jscomp.polyfills={};
$jscomp.propertyToPolyfillSymbol={};$jscomp.POLYFILL_PREFIX="$jscp$";var $jscomp$lookupPolyfilledValue=function(a,b){var c=$jscomp.propertyToPolyfillSymbol[b];if(null==c)return a[b];c=a[c];return void 0!==c?c:a[b]};$jscomp.polyfill=function(a,b,c,d){b&&($jscomp.ISOLATE_POLYFILLS?$jscomp.polyfillIsolated(a,b,c,d):$jscomp.polyfillUnisolated(a,b,c,d))};
$jscomp.polyfillUnisolated=function(a,b,c,d){c=$jscomp.global;a=a.split(".");for(d=0;d<a.length-1;d++){var e=a[d];if(!(e in c))return;c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&$jscomp.defineProperty(c,a,{configurable:!0,writable:!0,value:b})};
$jscomp.polyfillIsolated=function(a,b,c,d){var e=a.split(".");a=1===e.length;d=e[0];d=!a&&d in $jscomp.polyfills?$jscomp.polyfills:$jscomp.global;for(var g=0;g<e.length-1;g++){var f=e[g];if(!(f in d))return;d=d[f]}e=e[e.length-1];c=$jscomp.IS_SYMBOL_NATIVE&&"es6"===c?d[e]:null;b=b(c);null!=b&&(a?$jscomp.defineProperty($jscomp.polyfills,e,{configurable:!0,writable:!0,value:b}):b!==c&&(void 0===$jscomp.propertyToPolyfillSymbol[e]&&($jscomp.propertyToPolyfillSymbol[e]=$jscomp.IS_SYMBOL_NATIVE?$jscomp.global.Symbol(e):
$jscomp.POLYFILL_PREFIX+e),$jscomp.defineProperty(d,$jscomp.propertyToPolyfillSymbol[e],{configurable:!0,writable:!0,value:b})))};$jscomp.underscoreProtoCanBeSet=function(){var a={a:!0},b={};try{return b.__proto__=a,b.a}catch(c){}return!1};$jscomp.setPrototypeOf=$jscomp.TRUST_ES6_POLYFILLS&&"function"==typeof Object.setPrototypeOf?Object.setPrototypeOf:$jscomp.underscoreProtoCanBeSet()?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null;
$jscomp.generator={};$jscomp.generator.ensureIteratorResultIsObject_=function(a){if(!(a instanceof Object))throw new TypeError("Iterator result "+a+" is not an object");};$jscomp.generator.Context=function(){this.isRunning_=!1;this.yieldAllIterator_=null;this.yieldResult=void 0;this.nextAddress=1;this.finallyAddress_=this.catchAddress_=0;this.finallyContexts_=this.abruptCompletion_=null};
$jscomp.generator.Context.prototype.start_=function(){if(this.isRunning_)throw new TypeError("Generator is already running");this.isRunning_=!0};$jscomp.generator.Context.prototype.stop_=function(){this.isRunning_=!1};$jscomp.generator.Context.prototype.jumpToErrorHandler_=function(){this.nextAddress=this.catchAddress_||this.finallyAddress_};$jscomp.generator.Context.prototype.next_=function(a){this.yieldResult=a};
$jscomp.generator.Context.prototype.throw_=function(a){this.abruptCompletion_={exception:a,isException:!0};this.jumpToErrorHandler_()};$jscomp.generator.Context.prototype["return"]=function(a){this.abruptCompletion_={"return":a};this.nextAddress=this.finallyAddress_};$jscomp.generator.Context.prototype.jumpThroughFinallyBlocks=function(a){this.abruptCompletion_={jumpTo:a};this.nextAddress=this.finallyAddress_};$jscomp.generator.Context.prototype.yield=function(a,b){this.nextAddress=b;return{value:a}};
$jscomp.generator.Context.prototype.yieldAll=function(a,b){var c=$jscomp.makeIterator(a),d=c.next();$jscomp.generator.ensureIteratorResultIsObject_(d);if(d.done)this.yieldResult=d.value,this.nextAddress=b;else return this.yieldAllIterator_=c,this.yield(d.value,b)};$jscomp.generator.Context.prototype.jumpTo=function(a){this.nextAddress=a};$jscomp.generator.Context.prototype.jumpToEnd=function(){this.nextAddress=0};
$jscomp.generator.Context.prototype.setCatchFinallyBlocks=function(a,b){this.catchAddress_=a;void 0!=b&&(this.finallyAddress_=b)};$jscomp.generator.Context.prototype.setFinallyBlock=function(a){this.catchAddress_=0;this.finallyAddress_=a||0};$jscomp.generator.Context.prototype.leaveTryBlock=function(a,b){this.nextAddress=a;this.catchAddress_=b||0};
$jscomp.generator.Context.prototype.enterCatchBlock=function(a){this.catchAddress_=a||0;a=this.abruptCompletion_.exception;this.abruptCompletion_=null;return a};$jscomp.generator.Context.prototype.enterFinallyBlock=function(a,b,c){c?this.finallyContexts_[c]=this.abruptCompletion_:this.finallyContexts_=[this.abruptCompletion_];this.catchAddress_=a||0;this.finallyAddress_=b||0};
$jscomp.generator.Context.prototype.leaveFinallyBlock=function(a,b){var c=this.finallyContexts_.splice(b||0)[0];if(c=this.abruptCompletion_=this.abruptCompletion_||c){if(c.isException)return this.jumpToErrorHandler_();void 0!=c.jumpTo&&this.finallyAddress_<c.jumpTo?(this.nextAddress=c.jumpTo,this.abruptCompletion_=null):this.nextAddress=this.finallyAddress_}else this.nextAddress=a};$jscomp.generator.Context.prototype.forIn=function(a){return new $jscomp.generator.Context.PropertyIterator(a)};
$jscomp.generator.Context.PropertyIterator=function(a){this.object_=a;this.properties_=[];for(var b in a)this.properties_.push(b);this.properties_.reverse()};$jscomp.generator.Context.PropertyIterator.prototype.getNext=function(){for(;0<this.properties_.length;){var a=this.properties_.pop();if(a in this.object_)return a}return null};$jscomp.generator.Engine_=function(a){this.context_=new $jscomp.generator.Context;this.program_=a};
$jscomp.generator.Engine_.prototype.next_=function(a){this.context_.start_();if(this.context_.yieldAllIterator_)return this.yieldAllStep_(this.context_.yieldAllIterator_.next,a,this.context_.next_);this.context_.next_(a);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.return_=function(a){this.context_.start_();var b=this.context_.yieldAllIterator_;if(b)return this.yieldAllStep_("return"in b?b["return"]:function(c){return{value:c,done:!0}},a,this.context_["return"]);this.context_["return"](a);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.throw_=function(a){this.context_.start_();if(this.context_.yieldAllIterator_)return this.yieldAllStep_(this.context_.yieldAllIterator_["throw"],a,this.context_.next_);this.context_.throw_(a);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.yieldAllStep_=function(a,b,c){try{var d=a.call(this.context_.yieldAllIterator_,b);$jscomp.generator.ensureIteratorResultIsObject_(d);if(!d.done)return this.context_.stop_(),d;var e=d.value}catch(g){return this.context_.yieldAllIterator_=null,this.context_.throw_(g),this.nextStep_()}this.context_.yieldAllIterator_=null;c.call(this.context_,e);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.nextStep_=function(){for(;this.context_.nextAddress;)try{var a=this.program_(this.context_);if(a)return this.context_.stop_(),{value:a.value,done:!1}}catch(b){this.context_.yieldResult=void 0,this.context_.throw_(b)}this.context_.stop_();if(this.context_.abruptCompletion_){a=this.context_.abruptCompletion_;this.context_.abruptCompletion_=null;if(a.isException)throw a.exception;return{value:a["return"],done:!0}}return{value:void 0,done:!0}};
$jscomp.generator.Generator_=function(a){this.next=function(b){return a.next_(b)};this["throw"]=function(b){return a.throw_(b)};this["return"]=function(b){return a.return_(b)};this[Symbol.iterator]=function(){return this}};$jscomp.generator.createGenerator=function(a,b){var c=new $jscomp.generator.Generator_(new $jscomp.generator.Engine_(b));$jscomp.setPrototypeOf&&a.prototype&&$jscomp.setPrototypeOf(c,a.prototype);return c};
$jscomp.asyncExecutePromiseGenerator=function(a){function b(d){return a.next(d)}function c(d){return a["throw"](d)}return new Promise(function(d,e){function g(f){f.done?d(f.value):Promise.resolve(f.value).then(b,c).then(g,e)}g(a.next())})};$jscomp.asyncExecutePromiseGeneratorFunction=function(a){return $jscomp.asyncExecutePromiseGenerator(a())};$jscomp.asyncExecutePromiseGeneratorProgram=function(a){return $jscomp.asyncExecutePromiseGenerator(new $jscomp.generator.Generator_(new $jscomp.generator.Engine_(a)))};
var myLocalQuestionsObject={questions:{}},curFilterInput="",filterInputGiven=!1,metadata={contentType:"image/jpeg"};$("#btnall").on("click",function(){var a=$("#inputall").val().trim();$("#inputall").val("");var b=a.split("@^&&^@");a=0;b=$jscomp.makeIterator(b);for(var c=b.next();!c.done;c=b.next())window.setTimeout(function(d){return function(){$("#inputquestion").val(d);$("#btn").click()}}(c.value),500*a),++a});
function calculateLevDistance(a,b){if(!a||!b)return!1;var c=a.length,d=b.length,e=[[]];if(c<d){var g=a;a=b;b=g;g=c;c=d;d=g}for(g=0;g<d+1;g++)e[0][g]=g;for(var f=1;f<c+1;f++){e[f]=[];e[f][0]=f;for(var h=1;h<d+1;h++)g=a.charAt(f-1)===b.charAt(h-1)?0:1,e[f][h]=Math.min(e[f-1][h]+1,e[f][h-1]+1,e[f-1][h-1]+g)}return e[c][d]}$("#btn").on("click",handleNewQuestion);
function handleNewQuestion(){var a=$("#inputquestion").val().trim();if(a.includes("<script")||0===a.length)return!1;$("#inputquestion").val("");var b=2*a.length;for(d in myLocalQuestionsObject.questions)if(myLocalQuestionsObject.questions.hasOwnProperty(d)){var c=myLocalQuestionsObject.questions[d];b=Math.min(b,calculateLevDistance(c.question,a))}if(5>b)console.log("Already exists");else{a={question:a};var d;firebase.database().ref("ffe_questions").push(a)}}
function handleNewComment(a,b){if(b.includes("<script"))return!1;var c={comment:b,upvote:0,downvote:0};return firebase.database().ref("ffe_questions/"+a+"/commentsArray").push(c)}document.getElementById("filter").addEventListener("input",function(a){curFilterInput=a.target.value;filterInputGiven=""==curFilterInput?!1:!0;filter(myLocalQuestionsObject.questions)});
function filter(a){if(filterInputGiven)for(questionKey in a){if(a.hasOwnProperty(questionKey)){var b=a[questionKey];$("#"+questionKey).hide();if(-1!=b.question.toLowerCase().indexOf(curFilterInput.toLowerCase()))$("#"+questionKey).show();else for(commentKey in b.commentsArray)if(b.commentsArray.hasOwnProperty(commentKey)){var c=b.commentsArray[commentKey];if(-1!=c.comment.toLowerCase().indexOf(curFilterInput.toLowerCase())){$("#"+questionKey).show();break}}}}else for(questionKey in a)a.hasOwnProperty(questionKey)&&
$("#"+questionKey).show()}function updateVote(a,b,c){if(myLocalQuestionsObject.questions=={}||!myLocalQuestionsObject.questions.hasOwnProperty(a))return!1;1==c?myLocalQuestionsObject.questions[a].commentsArray[b].upvote+=1:myLocalQuestionsObject.questions[a].commentsArray[b].downvote+=1;b={};b["/ffe_questions/"+a]=myLocalQuestionsObject.questions[a];firebase.database().ref().update(b)}var question_count=0;
function updateQuestionDOM(a,b){b=void 0===b?!1:b;if(b){var c=document.getElementById(a);c.innerHTML="Updating..."}else c=document.createElement("div"),c.setAttribute("class","bgff"),c.setAttribute("id",a),question_count++;0<question_count&&$("#loading").hide();var d=myLocalQuestionsObject.questions[a],e=document.createElement("p");e.innerHTML=d.question;e.setAttribute("class","qColor");var g=document.createElement("ul"),f=document.createElement("input");f.setAttribute("placeholder","add new answer");
var h=document.createElement("button");h.innerText="Submit ans";h.setAttribute("class","btnx");h.addEventListener("click",function(k){k=f.value.trim();if(0===k.length)return!1;handleNewComment(a,k)});f.addEventListener("keydown",function(k){if("Enter"===k.code||"NumpadEnter"==k.code){k=f.value.trim();if(0===k.length)return!1;handleNewComment(a,k)}});g.appendChild(f);g.appendChild(h);if(d.commentsArray)for(commentKey in d.commentsArray)if(d.commentsArray.hasOwnProperty(commentKey)){var l=d.commentsArray[commentKey];
h=document.createElement("li");var n=document.createElement("span");n.innerHTML=l.comment;n.setAttribute("class","combg");$votes=document.createElement("span");$votes.innerHTML="Votes: "+(l.upvote-l.downvote);l=document.createElement("button");l.setAttribute("class","btnx");l.setAttribute("id",a+"$$"+commentKey);l.innerHTML="up";l.addEventListener("click",function(k){k=k.target.id.split("$$");updateVote(k[0],k[1],1)},{once:!0});var m=document.createElement("button");m.innerHTML="down";m.setAttribute("class",
"btnx");m.setAttribute("id",a+"$$"+commentKey);m.addEventListener("click",function(k){k=k.target.id.split("$$");updateVote(k[0],k[1],-1)},{once:!0});h.appendChild($votes);h.appendChild(l);h.appendChild(m);h.appendChild(n);g.appendChild(h)}c.innerHTML="";c.appendChild(e);c.appendChild(g);b||document.getElementById("livesection").appendChild(c)}
function fetchAll(){var a,b;return $jscomp.asyncExecutePromiseGeneratorProgram(function(c){if(1==c.nextAddress)return a=firebase.database(),c.yield(a.ref("ffe_questions/"),2);b=c.yieldResult;b.on("child_added",function(d){function e(f){return $jscomp.asyncExecutePromiseGeneratorProgram(function(h){myLocalQuestionsObject.questions[d.key][f.key]=f.val();updateQuestionDOM(d.key,!0);h.jumpToEnd()})}var g;return $jscomp.asyncExecutePromiseGeneratorProgram(function(f){if(1==f.nextAddress)return f.yield(a.ref("ffe_questions/"+
d.key),2);g=f.yieldResult;myLocalQuestionsObject.questions[d.key]=d.val();updateQuestionDOM(d.key);g.on("child_changed",e);g.on("child_added",e);filter(myLocalQuestionsObject.questions);f.jumpToEnd()})});c.jumpToEnd()})}
var FFZZ=[527600736,-589989265,372879977,447338135,521919843,-1830535072,-1248500820,-1076934028,544126340,251437670,-841051550,-1997410943,835092320,816134498,-2137884095,-1217876447,1968398547,-90260357,-476978997,-888809510,1766371920,1706254585,353535965,-2050401371,845893951,-1078545862,-1851029633,-1973927804,-1194039966,-864596553,-583174992,-1076757537,1849485868,1798638304,368904646,-17205004,939682051,407294410,-1761177958,425204862,-1190342866,2449877,160669371,-1248408629,1706341016,1309132755,
-240487642,-986040381,1849366831,-1766003322,1596478313,81057117,930169954,819380921,-60887363,-1200852706,140344988,-1334939272,1710040898,-1166304507,2032339233,541241536,-1050711902,-1945139383,-1825020253,-921078025],digest=function(a){var b=void 0===a.algorithm?"SHA-256":a.algorithm,c=a.message,d,e,g;return $jscomp.asyncExecutePromiseGeneratorProgram(function(f){return 1==f.nextAddress?(d=Array.prototype.map,e=d.call,g=Uint8Array,f.yield(crypto.subtle.digest(b,(new TextEncoder).encode(c)),2)):
f["return"](e.call(d,new g(f.yieldResult),function(h){return("0"+h.toString(16)).slice(-2)}).join(""))})};digest({message:"hello"}).then(console.log);$("#main").hide();firebase.auth().onAuthStateChanged(function(a){a?FFZZ.includes(a.phoneNumber.split("").reduce(function(b,c){b=(b<<5)-b+c.charCodeAt(0);return b&b},0))?($("#main").show(),fetchAll()):(alert("No Entry"),window.location.href="login.html"):window.location.href="login.html"},function(a){console.log(a)});
document.onpaste=function(a){var b,c,d,e,g,f;return $jscomp.asyncExecutePromiseGeneratorProgram(function(h){b=firebase.storage().ref();c=(a.clipboardData||a.originalEvent.clipboardData).items;for(index in c)d=c[index],"file"===d.kind&&(e=d.getAsFile(),g=Math.random().toString(36).substring(7),f=b.child("images/"+g).put(e,metadata),$("#imgstatus").val("Uploading"),f.on("state_changed",function(l){},function(l){},function(){f.snapshot.ref.getDownloadURL().then(function(l){l="<img src='"+l+"'/>";$("#imgstatus").val("Uploaded! (Ready.)");
$("#inputquestion").val(l);$("#btn").click()})}));h.jumpToEnd()})};